### ISSUE TITLE
Implement CORS support

### ISSUE THREAD

**Issue by LeoBorai** [http-server-rs/http-server#4]
**Description**

Implement support for CORS headers. By default this server will not provide CORS headers on responses.

**Why is this useful?**

CORS headers would allow arbitrary front-ends to request resources to an instance of this server.
By default websites doesn't allow cross origin requests.

By providing CORS headers front-ends will be able to make request to the server and load such resources.

For more details refer to: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**How should this work?**

When running the HTTP server as:

```shell
http-server
```

Responses won't include any of CORS headers. Causing browsers to complain about missing
CORS headers when request are executed.

If the user runs the HTTP server specifying the `cors` option with the correct values, such browser
will be able to load such resources.

```shell
# Specifies CORS headers Origin to be "*" with all methods allowed and all headers allowed
http-server --cors

# Specifies CORS headers for the provided URL as origin
http-server --cors https://www.mywebsite.com
```

For further configuration the TOML configuration file must be used.

```toml
[cors]
origin = "https://www.mywebsite.com"
methods = ["GET", "POST", "PUT", "DELETE"]
headers = ["Content-Type"]
max-age = 3400
```
